name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create coverage config file
      run: |
        touch .coveragerc
        echo -e "[run] \nomit = eolzoom/migrations/*" > .coveragerc
    - name: Run Tests
      run: |
        cd .github/
        docker-compose run lms /openedx/requirements/eolzoom/.github/test.sh
    
